import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "../components/Header";
import AuthProvider from "../context/Provider";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="max-w-screen-xl min-h-screen flex flex-col h-screen scrollbar-none overflow-x-hidden">
				<AuthProvider>
					<Header />
					<div className="overflow-x-hidden overflow-y-scroll scrollbar-thin scrollbar-thumb-red-500 scrollbar-track-red-50">
						{children}
					</div>
				</AuthProvider>
			</body>
		</html>
	);
}
